name: l_and_u
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  firebase_core :
  firebase_database: ^9.0.8
  provider: ^6.0.2
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  flutter_slidable: ^1.2.0
  lottie: ^1.3.0
  firebase_auth: ^3.4.2
  email_validator: ^2.0.1
  flutter_easyloading: ^3.0.3
  
  animated_splash_screen: ^1.3.0
  location: ^4.4.0
  google_maps_flutter: ^2.1.8
  im_stepper: ^1.0.1+1
  flutter_geocoder: ^0.2.2-nullsafety
  geocoding: ^2.0.4
  dotted_line: ^3.1.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/lf30_editor_sdg75swn.json
    - assets/lf20_h2d0cota.json
    - assets/map.json
    - assets/66760-box-package.json
    - assets/lf20_izt3mhdr.json

  
  fonts:
    - family: Valentina
      fonts:
        - asset: assets/font/Best Valentina TTF.ttf
          weight : 100
    - family: Alice
      fonts:          
        - asset : assets/font/Alice-Regular.ttf
          weight : 200
 
